// scripts/seed.js
import { Pool } from 'pg';
import bcrypt from 'bcrypt';
import dotenv from 'dotenv';
import { config } from 'dotenv';

import fs from 'fs'; // if you need file checks

dotenv.config();
config({ path: '.env.local' });

  console.log('Current dir:', process.cwd());
//console.log('Exists?', require('fs').existsSync('.env.local'))

if (!process.env.DATABASE_URL) {
  
  console.error('❌ Missing DATABASE_URL in .env.local');
  process.exit(1);
}

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: process.env.NODE_ENV === 'production' 
    ? { rejectUnauthorized: false } 
    : false,
});

async function setupDatabase() {
  console.log('🔍 Checking database schema...');

  // ===== 1. Create tables if they don't exist =====
  await pool.query(`
    CREATE TABLE IF NOT EXISTS packages (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      slug TEXT NOT NULL UNIQUE,
      offered_by TEXT,
      tour_operator TEXT,
      rating NUMERIC(2,1),
      review_count INTEGER,
      short_description TEXT,
      full_description TEXT,
      duration INTEGER,
      price NUMERIC(10,2),
      starting_from TEXT,
      comfort_level TEXT,
      tour_type TEXT,
      safari_type TEXT,
      specialized_tours JSONB,
      features JSONB,
      image TEXT,
      highlights JSONB,
      destinations JSONB,
      route JSONB,
      tour_features JSONB,
      activities_transportation JSONB,
      accommodation_meals JSONB,
      gallery JSONB,
      day_by_day JSONB,
      rates JSONB,
      inclusions JSONB,
      getting_there JSONB,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS blogs (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      title TEXT NOT NULL,
      slug TEXT NOT NULL UNIQUE,
      date TEXT,
      read_time TEXT,
      excerpt TEXT,
      image TEXT,
      tags JSONB,
      author JSONB,
      content JSONB,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS admins (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      email TEXT NOT NULL UNIQUE,
      password_hash TEXT NOT NULL,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );
  `);

  console.log('✅ Tables created (if missing)');

  // ===== 2. Create default admin if none exists =====
  const { rows: admins } = await pool.query('SELECT id FROM admins LIMIT 1');
  if (admins.length === 0) {
    const defaultEmail = 'admin@asiliexplorer.com';
    const defaultPassword = 'secure_password_123'; // ⚠️ Change this!

    const hash = await bcrypt.hash(defaultPassword, 10);
    await pool.query(
      'INSERT INTO admins (email, password_hash) VALUES ($1, $2)',
      [defaultEmail, hash]
    );
    console.log(`✅ Default admin created:`);
    console.log(`   Email: ${defaultEmail}`);
    console.log(`   Password: ${defaultPassword}`);
    console.log(`⚠️  CHANGE THIS PASSWORD AFTER FIRST LOGIN!`);
  } else {
    console.log('ℹ️  Admin already exists — skipping');
  }

  // ===== 3. Create indexes =====
  await pool.query('CREATE INDEX IF NOT EXISTS idx_packages_slug ON packages(slug);');
  await pool.query('CREATE INDEX IF NOT EXISTS idx_blogs_slug ON blogs(slug);');
  console.log('✅ Indexes created');

  console.log('\n🎉 Database setup complete!');
  await pool.end();
}

setupDatabase().catch(err => {
  console.error('❌ Setup failed:', err);
  process.exit(1);
});